### ISSUE TITLE
This file is restricted - sensitivity label applied to the pbit preventing it from opening

### ISSUE THREAD

**Issue by ratson31** [szenatti/power-bi-azure-consumption#2]
Upon opening the pbit file in Power BI Desktop (latest version) I get the message 'This file is restricted. Your organization has protected this file with a sensitivity label. To request access contact your teams Power BI admin.' The file then fails to open.

Occurs both inside and outside of my organization.

Many thanks.

**Comment by szenatti** [comment]
Sensitivity label removed.
